### ISSUE TITLE
Import "terms and definitions" from standard documents into Glossarist module and incorporate data into model

### ISSUE THREAD

**Issue by wkwong-ribose** [paneron/extension-hls#41]

**Comment by wkwong-ribose** [comment]
@strogonoff I got the following error while I am testing Glossarist.

I created a new dataset for glossarist and used the original Glossarist UI. 
I can add concept and concept description.

<img width="1140" alt="Screen Shot 2021-11-15 at 1 30 43 PM" src="https://user-images.githubusercontent.com/80878223/141727598-7f15664e-7da2-4b2c-8827-71d0d2c2e132.png">

When I double click on any item (say abc in my screenshot), I get the error below.

<img width="1140" alt="Screen Shot 2021-11-15 at 1 27 19 PM" src="https://user-images.githubusercontent.com/80878223/141727315-f3d4f0f0-6a6e-485f-a040-dbcae03b07be.png">

Error log
```
Error rendering view dataset Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Mon%20Nov%2015%202021%2013%3A15%3A43%20GMT%2B0800%20(Hong%20Kong%20Standard%20Time)&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Qg (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:139:47)
    at Yg (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:149:278)
    at R (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:173:103)
    at Rj (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:265:156)
    at Qj (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:246:265)
    at Kj (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:246:194)
    at c (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:239:172)
    at b (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
    at If (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
    at cg (file:///Applications/Paneron.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:122:325) {
  componentStack: '\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in ChangeHistoryItem\n' +
    '    in ChangeHistory\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in SidebarBlock\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in Sidebar\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in Workspace\n' +
    '    in EmotionCssPropInternal\n' +
    '    in ItemDetails\n' +
    '    in RegisterItemBrowser\n' +
    '    in RegistryView\n' +
    '    in RepositoryView\n' +
    '    in Unknown\n' +
    '    in ErrorBoundary_ErrorBoundary\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in Context\n' +
    '    in MainWindow_Dataset\n' +
    '    in MainWindow_MainView\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in div\n' +
    '    in EmotionCssPropInternal\n' +
    '    in context\n' +
    '    in StrictMode\n' +
    '    in Unknown'
}
```

I am using a private working copy, if this is relevant.

**Comment by strogonoff** [comment]
@wkwong-ribose  Glossarist is based on RegistryKit, which is undergoing a big update, which includes tabbed interface and so on. There may be a temporary regression due to version mismatch (Paneron is bundling pre-update RegistryKit, but Glossarist depends on post-update RegistryKit).

**Comment by strogonoff** [comment]
According to the error, it has to do with datetime representation.

**Comment by wkwong-ribose** [comment]
Thanks @strogonoff. Guess I won't be working on this in a short time.
